classdef SpectrumRunnerTest < matlab.unittest.TestCase
    % Smoke tests on the SpectrumRunner -- exercises the full pipeline
    % on the smallest config that the original code accepted.

    methods (Test)
        function smallRunCompletes(tc)
            cfg = rcwa.Config('Nt', 2, 'Nx', 11, 'nlambda', 2, ...
                              'nmlambda0', 500, 'nmlambda1', 600, ...
                              'Nm', 1, 'Ng', 0, 'Nz', 2, 'Nw', 1, 'Nair', 1, ...
                              'nmda', 0, 'nmLg', 0, 'nmLp', 5, ...
                              'nmLi', 50, 'nmLn', 5, 'nmLm', 50, ...
                              'nmLw', 20, 'nmLair', 100, ...
                              'gmat', 0, 'dmat', 0, 'wmat', 0, ...
                              'material', 0, ...
                              'plotting', 0, 'parforArg', 0, ...
                              'epsm', 1+3i, 'epsd', 4+0i, ...
                              'epsJ', 9+0.2i, 'epsW', 3+1e-6i, 'nsa', 1);
            runner = rcwa.SpectrumRunner(cfg);
            out = runner.run();
            tc.verifySize(out.nmlambda, [1, cfg.nlambda]);
            tc.verifyFalse(any(isnan(out.r0(:))), 'r0 has NaN');
            tc.verifyFalse(isnan(out.mAicm2JOpt), 'JOpt is NaN');
            tc.verifyGreaterThanOrEqual(out.mAicm2JOpt, 0, ...
                'JOpt should be non-negative');
        end

        function deterministicReproducibility(tc)
            % Two identical runs must yield identical numbers.
            cfg = rcwa.Config('Nt', 2, 'Nx', 11, 'nlambda', 1, ...
                              'nmlambda0', 550, 'nmlambda1', 550, ...
                              'Nm', 1, 'Ng', 0, 'Nz', 1, 'Nw', 1, 'Nair', 1, ...
                              'nmda', 0, 'nmLg', 0, ...
                              'gmat', 0, 'dmat', 0, 'wmat', 0, 'material', 0, ...
                              'plotting', 0, 'parforArg', 0);
            runner = rcwa.SpectrumRunner(cfg);
            a = runner.run();
            b = runner.run();
            tc.verifyEqual(a.mAicm2JOpt, b.mAicm2JOpt, 'AbsTol', 0);
        end

        function junctionSliceThicknessGuardsZero(tc)
            % BUG-009 regression: original divided by Nz unguarded; OOP
            % version returns 0 in that case rather than NaN.
            cfg = rcwa.Config('Nz', 0, 'Nair', 1, 'Nm', 1);
            cfg = cfg.verify();
            runner = rcwa.SpectrumRunner(cfg);
            tc.verifyEqual(runner.junctionSliceThickness(), 0);
        end
    end
end
